---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parse_opponent(parse_opponent)
	choose_frame(choose_frame)
	search_web(search_web)
	select_tactic(select_tactic)
	draft_argument(draft_argument)
	apply_character(apply_character)
	polish_onpc(polish_onpc)
	__end__([<p>__end__</p>]):::last
	__start__ --> parse_opponent;
	apply_character --> polish_onpc;
	choose_frame -.-> search_web;
	choose_frame -.-> select_tactic;
	draft_argument --> apply_character;
	parse_opponent --> choose_frame;
	search_web --> select_tactic;
	select_tactic --> draft_argument;
	polish_onpc --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
